version: "3.9"

services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: inventario-sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourSecretPassw0rd!
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  backend:
    build:
      context: ./backend/Backend
      dockerfile: Dockerfile
    container_name: inventario-backend
    depends_on:
      - sql
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=sql;Database=InventarioTI;User=sa;Password=YourSecretPassw0rd!;TrustServerCertificate=True;"
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend/frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://localhost:8080   
    container_name: inventario-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"


volumes:
  sql_data:
